### ISSUE TITLE
Incomplete kernel module source code.

### ISSUE THREAD

**Issue by arter97** [NothingOSS/android_kernel_msm-5.10_nothing_sm8475#2]
Hi.

It seems that Nothing didn't release some of the kernel module's source code that would immediately block developing a custom kernel with modules built-in.

Specifically, Qualcomm (forked) kernel modules are missing:
- camera-kernel
- cvp-kernel
- eva-kernel
- video-driver
- mmrm-driver
- dataipa
- datarmnet-ext
- datarmnet

All of those modules are licensed with GPL v2, and just like the main kernel source code, it is required for those to be published as well.
Please address this as soon as possible.

(To avoid future mistakes like this, please look for Kbuild files on the Android build source tree (`find * -name Kbuild`) and make sure you have not missed out any potential repositories for publishing. All of those modules aforementioned have the Linux kernel-specific Kbuild file on the repo.)

Thanks.

**Comment by ghost** [comment]
OnePlus 11 has full device tree already

**Comment by arter97** [comment]
> OnePlus 11 has full device tree and is better hardware wise.

How is that even remotely related to this issue? Please don't post off-topic comment that doesn't help the situation in any way.

**Comment by arter97** [comment]
Bump.

**Comment by spakkkk** [comment]
Bump!

**Comment by jaack08** [comment]
Wen!!

**Comment by luka177** [comment]
bump

**Comment by Dark-Matter7232** [comment]
@NothingOSS gib arter his kernel modules pls

**Comment by sagarshah1729** [comment]
Bump!

**Comment by nezorflame** [comment]
@NothingOSS would really like a reply here.

**Comment by NothingOSS** [comment]
We are working on it and will update you soon.
Thank you for your patience.

**Comment by spike0en** [comment]
> We are working on it and will update you soon. Thank you for your patience.

Thank you for the update! Your support for open source development is greatly appreciated.

**Comment by schyler2011** [comment]
@NothingOSS Shouldn't be something you have to work on... Just publish.

**Comment by arter97** [comment]
It appears that the touchscreen code is also missing some bits.

In Nothing OS 2.0.3, vendor_dlkm contains /lib/modules/goodix_core.ko, which is licensed as GPL v2.

The symbol `replay_module_init` is present on the firmware but not on the released source code.

Please review @NothingOSS.

**Comment by capntrips** [comment]
A few commits were added recently, and one of them (c553bb6) seems to address this issue. I'm new to tinkering with kernels, so I can't say if it resolves the issue, but I wanted to mention it, since it has gone unremarked.

**Comment by arter97** [comment]
Dear @NothingOSS, I commend the effort to address everything mentioned here.

All module's source code has been released, most notably the camera module which was `CAMERA.LA.2.0.r1-08700-WAIPIO.0` with no modifications, as well as the missing Goodix replay source and the device-tree (dts/dtsi) that I complained on the forum.

Thanks for that, but I have to mention I'm still frowning upon the state of unsynced source releases with OTA. Please see #3.
