### ISSUE TITLE
Release kernel sources (in order to comply with GPL-v2) for the Nothing Phone (2a) (`Pacman`)

### ISSUE THREAD

**Issue by ant14181** [NothingOSS/android_kernel_msm-5.10_nothing_sm8475#6]
Hello,

the Nothing Phone (2a) has been released on the 5th of March in India, and 6th of the same month globally.
Releasing the kernel source for the device, along with MediaTek's and Nothing's kernel modules, would help with the development for said device.

### Informations
 * `ro.nothing.version.id`: `2.5.3`
    * `ro.build.display.id`: `U2.5-240301-2206`
 * `ro.vendor.build.fingerprint`: `Nothing/Pacman/Pacman:13/TP1A.220624.014/2403012206:user/release-keys`
 * `ro.vendor.build.id`: `TP1A.220624.014`

**Comment by halal-beef** [comment]
I agree, development good, no kernel source bad

@NothingOSS pls release

**Comment by plarfman** [comment]
I hope you Poo

**Comment by Nakamerica** [comment]
Please release the kernel src for the 2a.
